type ClientMessage={role:'student'|'tutor';text:string}
type LabContext={componentId:string;lesson:string;interactionState:string;handTracking:boolean;gesture:string|null;visited:string[];passed:string[];availableActions:string[];component:{name:string;summary:string;role:string;analogy:string}}
const encoder=new TextEncoder()
const defaultOrigins=['https://devsmaj.github.io','http://localhost:5173','http://127.0.0.1:5173','http://127.0.0.1:4173']

function cors(request:Request){const origin=request.headers.get('origin')??'';const configured=(Deno.env.get('ALLOWED_ORIGINS')??'').split(',').map(value=>value.trim()).filter(Boolean);const allowed=[...defaultOrigins,...configured];return{'Access-Control-Allow-Origin':allowed.includes(origin)?origin:defaultOrigins[0],'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Expose-Headers':'x-nova-request-id','Vary':'Origin'}}
function jsonError(request:Request,status:number,message:string,code:string){return new Response(JSON.stringify({error:{message,code}}),{status,headers:{...cors(request),'Content-Type':'application/json'}})}
function sse(value:unknown){return encoder.encode(`data: ${JSON.stringify(value)}\n\n`)}
function text(value:unknown,max:number){return typeof value==='string'?value.trim().slice(0,max):''}
function validContext(value:unknown):value is LabContext{if(!value||typeof value!=='object')return false;const item=value as Record<string,unknown>;return typeof item.componentId==='string'&&typeof item.lesson==='string'&&typeof item.interactionState==='string'&&typeof item.component==='object'&&item.component!==null}

Deno.serve(async request=>{
 const headers=cors(request)
 if(request.method==='OPTIONS')return new Response(null,{status:204,headers})
 if(request.method!=='POST')return jsonError(request,405,'Only POST is supported.','method_not_allowed')
 const origin=request.headers.get('origin');if(origin&&headers['Access-Control-Allow-Origin']!==origin)return jsonError(request,403,'This origin is not allowed.','origin_forbidden')
 const apiKey=Deno.env.get('OPENAI_API_KEY');if(!apiKey)return jsonError(request,503,'NOVA is unavailable because the OpenAI server secret is not configured.','openai_not_configured')
 let payload:Record<string,unknown>
 try{payload=await request.json()}catch{return jsonError(request,400,'The NOVA request body is not valid JSON.','invalid_json')}
 const message=text(payload.message,2000),context=payload.context
 if(!message)return jsonError(request,400,'A transcript or message is required.','message_required')
 if(!validContext(context))return jsonError(request,400,'Valid SMAJ 3D Lab context is required.','context_required')
 const history=(Array.isArray(payload.history)?payload.history:[]).slice(-12).flatMap((entry:unknown)=>{if(!entry||typeof entry!=='object')return[];const item=entry as Record<string,unknown>,content=text(item.text,2000);if(!content||!['student','tutor'].includes(String(item.role)))return[];return[{role:item.role==='student'?'user':'assistant',content}]})
 const safeContext={selectedComponent:{id:text(context.componentId,40),name:text(context.component.name,120),lesson:text(context.lesson,240),summary:text(context.component.summary,1200),role:text(context.component.role,400),analogy:text(context.component.analogy,500)},interaction:{view:text(context.interactionState,40),handTracking:Boolean(context.handTracking),gesture:text(context.gesture,60)||null},progress:{visited:Array.isArray(context.visited)?context.visited.slice(0,20):[],passed:Array.isArray(context.passed)?context.passed.slice(0,20):[]},availableActions:Array.isArray(context.availableActions)?context.availableActions.slice(0,20):[]}
 const instructions=`You are NOVA, the live educational AI inside SMAJ 3D Lab. Teach accurately, clearly, and concisely. Use the current lab context below to understand references such as "this", "it", "this part", and "why". Explain what the learner is actually viewing and suggest only actions that appear in availableActions. Never claim that a camera, gesture, component, quiz, or action occurred unless the context says it did. If information is uncertain, say so. Prefer 2-5 short sentences unless the learner asks for detail. Current lab context: ${JSON.stringify(safeContext)}`
 let upstream:Response
 try{upstream=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:Deno.env.get('OPENAI_MODEL')??'gpt-5-mini',instructions,input:[...history,{role:'user',content:message}],max_output_tokens:400,stream:true,store:false}),signal:request.signal})}catch(error){return jsonError(request,502,`OpenAI connection failed: ${error instanceof Error?error.message:'network error'}.`,'openai_connection_error')}
 if(!upstream.ok){let detail=`HTTP ${upstream.status}`;try{const body=await upstream.json();detail=body?.error?.message??detail}catch{/* retain status */}const code=upstream.status===429?'openai_rate_limit':upstream.status===401?'openai_auth_error':'openai_api_error';return jsonError(request,upstream.status===429?429:502,`OpenAI request failed: ${detail}`,code)}
 if(!upstream.body)return jsonError(request,502,'OpenAI returned an empty response stream.','openai_empty_stream')
 const requestId=upstream.headers.get('x-request-id')??crypto.randomUUID(),reader=upstream.body.getReader(),decoder=new TextDecoder()
 const stream=new ReadableStream<Uint8Array>({async start(controller){let buffer='';try{while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()??'';for(const block of blocks){const dataLine=block.split(/\r?\n/).find(line=>line.startsWith('data:'));if(!dataLine)continue;const raw=dataLine.slice(5).trim();if(raw==='[DONE]')continue;let event:Record<string,any>;try{event=JSON.parse(raw)}catch{continue}if(event.type==='response.output_text.delta'&&typeof event.delta==='string')controller.enqueue(sse({type:'delta',delta:event.delta}));if(event.type==='error'||event.type==='response.failed'){const issue=event.error??event.response?.error;controller.enqueue(sse({type:'error',message:issue?.message??'OpenAI could not complete the response.',code:issue?.code??'openai_stream_error'}))}}if(done)break}controller.enqueue(sse({type:'done'}));controller.close()}catch(error){controller.enqueue(sse({type:'error',message:error instanceof Error?error.message:'NOVA stream interrupted.',code:'stream_error'}));controller.close()}},cancel(){void reader.cancel()}})
 return new Response(stream,{headers:{...headers,'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','X-Content-Type-Options':'nosniff','x-nova-request-id':requestId}})
})
