import { Check, CircleHelp, ChevronRight, Rotate3D } from 'lucide-react'
import { useEffect, useState } from 'react'
import { componentById, components } from '../../data/components'
import { useLabStore } from '../../store/labStore'

export function ModelInfo(){
 const selected=useLabStore(s=>s.selectedComponent),select=useLabStore(s=>s.selectComponent),visited=useLabStore(s=>s.visited),recordQuiz=useLabStore(s=>s.recordQuiz),quizResults=useLabStore(s=>s.quizResults);const component=componentById[selected];const index=components.findIndex(item=>item.id===selected);const[quiz,setQuiz]=useState(false);const[answer,setAnswer]=useState<number|null>(null)
 useEffect(()=>{setQuiz(false);setAnswer(null)},[selected])
 const next=components[(index+1)%components.length]
 return <aside className="info-panel lesson-panel" aria-live="polite"><div className="lesson-progress"><span>Lesson {index+1} of {components.length}</span><span>{visited.length}/{components.length} explored / {Object.values(quizResults).filter(Boolean).length} passed</span></div><div className="component-tabs" aria-label="Computer components">{components.map(item=><button key={item.id} className={item.id===selected?'active':''} onClick={()=>select(item.id)} aria-pressed={item.id===selected}>{visited.includes(item.id)?<Check size={11}/>:null}{item.shortName}</button>)}</div>{quiz?<div className="quiz-card"><div className="eyebrow"><CircleHelp size={15}/>Knowledge check</div><h3>{component.quiz.question}</h3><div className="quiz-options">{component.quiz.options.map((option,optionIndex)=>{const chosen=answer===optionIndex;const correct=answer!==null&&optionIndex===component.quiz.answer;return <button key={option} onClick={()=>{setAnswer(optionIndex);recordQuiz(selected,optionIndex===component.quiz.answer)}} disabled={answer!==null} className={correct?'correct':chosen?'incorrect':''}>{option}</button>})}</div>{answer!==null?<p className={answer===component.quiz.answer?'quiz-result success':'quiz-result'}>{answer===component.quiz.answer?'Correct. ':'Not quite. '}{component.quiz.explanation}</p>:null}<button className="text-button" onClick={()=>{setQuiz(false);setAnswer(null)}}>Back to lesson</button></div>:<><div className="eyebrow"><Rotate3D size={15}/>{component.lesson}</div><h2>{component.name}</h2><p>{component.summary}</p><div className="fact"><span>Core role</span><strong>{component.role}</strong></div><div className="analogy"><span>Think of it like</span><p>{component.analogy}</p></div><div className="lesson-actions"><button onClick={()=>setQuiz(true)}>Quiz me</button><button onClick={()=>select(next.id)}>Next: {next.shortName}<ChevronRight size={15}/></button></div></>}</aside>
}
