import { Html, RoundedBox } from '@react-three/drei'
import type { ThreeEvent } from '@react-three/fiber'
import { useMemo } from 'react'
import { componentById, type ComponentId } from '../../data/components'
import { useLabStore } from '../../store/labStore'

type Props={rotation:[number,number,number]}
const metal={color:'#b9c1c4',metalness:.82,roughness:.2} as const
const dark={color:'#171b1d',metalness:.68,roughness:.26} as const
const board={color:'#252b2d',metalness:.36,roughness:.48} as const
const gold={color:'#c6a35a',metalness:.86,roughness:.2} as const
function Chip({position=[0,0,0],scale=[1,1,1]}:{position?:[number,number,number];scale?:[number,number,number]}){return <RoundedBox position={position} scale={scale} radius={.06} smoothness={3}><meshStandardMaterial {...dark}/></RoundedBox>}
function Cpu(){const pins=useMemo(()=>Array.from({length:11},(_,i)=>(i-5)*.19),[]);return <group><RoundedBox args={[2.35,.22,2.35]} radius={.12} smoothness={4}><meshStandardMaterial {...dark}/></RoundedBox><RoundedBox position={[0,.18,0]} args={[1.78,.16,1.78]} radius={.07} smoothness={3}><meshStandardMaterial {...metal}/></RoundedBox><mesh position={[0,.275,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[1.2,1.2]}/><meshStandardMaterial color="#dce1e2" metalness={.9} roughness={.12}/></mesh>{pins.map((v,i)=><group key={i}><mesh position={[-1.2,-.15,v]}><boxGeometry args={[.1,.1,.08]}/><meshStandardMaterial {...gold}/></mesh><mesh position={[1.2,-.15,v]}><boxGeometry args={[.1,.1,.08]}/><meshStandardMaterial {...gold}/></mesh><mesh position={[v,-.15,-1.2]}><boxGeometry args={[.08,.1,.1]}/><meshStandardMaterial {...gold}/></mesh><mesh position={[v,-.15,1.2]}><boxGeometry args={[.08,.1,.1]}/><meshStandardMaterial {...gold}/></mesh></group>)}</group>}
function Ram(){const chips=useMemo(()=>Array.from({length:8},(_,i)=>-2.05+i*.59),[]);const contacts=useMemo(()=>Array.from({length:28},(_,i)=>-2.42+i*.18),[]);return <group><RoundedBox args={[5.2,1.25,.12]} radius={.08} smoothness={3}><meshStandardMaterial {...board}/></RoundedBox>{chips.map((x,i)=><Chip key={i} position={[x,.12,.13]} scale={[.43,.55,.13]}/>) }{contacts.map((x,i)=><mesh key={i} position={[x,-.66,.02]}><boxGeometry args={[.11,.22,.08]}/><meshStandardMaterial {...gold}/></mesh>)}<mesh position={[0,.25,-.08]}><boxGeometry args={[4.7,.035,.04]}/><meshStandardMaterial color="#8d999c" emissive="#677274" emissiveIntensity={.35}/></mesh><RoundedBox position={[0,.78,0]} args={[1.4,.18,.16]} radius={.06}><meshStandardMaterial {...metal}/></RoundedBox></group>}
function Gpu(){const fan=(x:number)=><group position={[x,0,.34]} rotation={[Math.PI/2,0,0]}><mesh><cylinderGeometry args={[.72,.72,.2,48]}/><meshStandardMaterial {...dark}/></mesh>{Array.from({length:9},(_,i)=><mesh key={i} rotation={[0,0,i*Math.PI*2/9]} position={[0,.13,0]}><boxGeometry args={[.16,.88,.07]}/><meshStandardMaterial color="#6f787b" metalness={.7} roughness={.25}/></mesh>)}<mesh position={[0,.25,0]}><cylinderGeometry args={[.2,.2,.24,32]}/><meshStandardMaterial {...metal}/></mesh></group>;return <group><RoundedBox args={[4.7,2.05,.35]} radius={.14} smoothness={4}><meshStandardMaterial {...board}/></RoundedBox>{fan(-1.2)}{fan(.65)}<RoundedBox position={[2.25,.15,0]} args={[.32,1.65,.5]} radius={.05}><meshStandardMaterial {...metal}/></RoundedBox><mesh position={[0,-1.08,0]}><boxGeometry args={[2.6,.16,.32]}/><meshStandardMaterial {...gold}/></mesh></group>}
function Ssd(){return <group><RoundedBox args={[3.8,.32,2.45]} radius={.17} smoothness={5}><meshStandardMaterial {...dark}/></RoundedBox><RoundedBox position={[0,.2,0]} args={[3.28,.12,1.92]} radius={.11} smoothness={4}><meshStandardMaterial {...metal}/></RoundedBox><mesh position={[0,.27,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[2.45,1.2]}/><meshStandardMaterial color="#eef1f1" metalness={.45} roughness={.36}/></mesh>{[[-1.55,.28,-.88],[1.55,.28,-.88],[-1.55,.28,.88],[1.55,.28,.88]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><cylinderGeometry args={[.08,.08,.06,20]}/><meshStandardMaterial {...dark}/></mesh>)}</group>}
function Cooling(){return <group><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[1.75,1.75,.38,64]}/><meshStandardMaterial {...dark}/></mesh>{Array.from({length:11},(_,i)=><mesh key={i} rotation={[0,0,i*Math.PI*2/11]} position={[0,.25,.08]}><boxGeometry args={[.2,1.45,.08]}/><meshStandardMaterial color="#8e989a" metalness={.7} roughness={.22}/></mesh>)}<mesh position={[0,.36,0]}><cylinderGeometry args={[.4,.4,.28,40]}/><meshStandardMaterial {...metal}/></mesh><mesh rotation={[Math.PI/2,0,0]}><torusGeometry args={[1.78,.09,12,64]}/><meshStandardMaterial {...metal}/></mesh></group>}
function Motherboard(){return <group><RoundedBox args={[5.7,.18,4.1]} radius={.1} smoothness={3}><meshStandardMaterial {...board}/></RoundedBox><Chip position={[-.35,.28,-.1]} scale={[1.35,.3,1.35]}/><Chip position={[1.9,.25,1.15]} scale={[.8,.26,.62]}/>{[-2,-1.55,-1.1,-.65].map((x,i)=><RoundedBox key={i} position={[x,.34,-.65]} args={[.24,.42,2.25]} radius={.05}><meshStandardMaterial {...metal}/></RoundedBox>)}{[-1.25,-.55,.15].map((z,i)=><RoundedBox key={i} position={[1.05,.28,z]} args={[2.5,.24,.18]} radius={.04}><meshStandardMaterial color={i===0?'#c8b36a':'#697276'} metalness={.65} roughness={.3}/></RoundedBox>)}{Array.from({length:10},(_,i)=><mesh key={i} position={[-2.45+i*.5,.2,1.65]}><boxGeometry args={[.08,.08,.8]}/><meshStandardMaterial color="#788285" emissive="#6f7b7d" emissiveIntensity={.25}/></mesh>)}</group>}
function SelectedPart({id}:{id:ComponentId}){if(id==='cpu')return <Cpu/>;if(id==='ram')return <Ram/>;if(id==='gpu')return <Gpu/>;if(id==='ssd')return <Ssd/>;if(id==='cooling')return <Cooling/>;return <Motherboard/>}
const scaleByComponent={motherboard:.82,cpu:1.15,ram:.84,gpu:.82,ssd:1,cooling:1.05} as const
export function Model({rotation}:Props){const selected=useLabStore(s=>s.selectedComponent),select=useLabStore(s=>s.selectComponent),component=componentById[selected];const choose=(event:ThreeEvent<MouseEvent>)=>{event.stopPropagation();select(selected)};return <group rotation={rotation} scale={scaleByComponent[selected]} onClick={choose} onPointerEnter={()=>document.body.style.cursor='grab'} onPointerLeave={()=>document.body.style.cursor='default'}><SelectedPart id={selected}/><Html position={[0,2.05,0]} center distanceFactor={9}><div className="solo-part-label"><span>ACTIVE_COMPONENT</span><strong>{component.shortName}</strong></div></Html></group>}