import { Environment, Html, OrbitControls, useProgress } from '@react-three/drei'
import { Canvas, useThree } from '@react-three/fiber'
import { Component, Suspense, useEffect, type ReactNode } from 'react'
import { Raycaster, Vector2 } from 'three'
import { componentIdFromModelName } from '../../data/components'
import { useLabStore } from '../../store/labStore'
import { Model } from './Model'
function Loading(){const{progress}=useProgress();return <Html center><div className="model-loading" role="status">Loading model - {Math.round(progress)}%</div></Html>}
class ModelError extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<Html center><div className="model-error" role="alert">The 3D model could not be loaded. Refresh to try again.</div></Html>:this.props.children}}
type Signal={id:number;x:number;y:number};type ZoomSignal={id:number;delta:number}
function GestureBridge({selection,zoom}:{selection:Signal|null;zoom:ZoomSignal|null;explode?:number}){const{camera,scene}=useThree();const select=useLabStore(s=>s.selectComponent);useEffect(()=>{if(!selection)return;scene.updateMatrixWorld(true);const raycaster=new Raycaster();raycaster.setFromCamera(new Vector2(selection.x*2-1,1-selection.y*2),camera);const hit=raycaster.intersectObjects(scene.children,true).find(item=>componentIdFromModelName(item.object.name));const id=hit?componentIdFromModelName(hit.object.name):undefined;if(id)select(id)},[selection?.id,camera,scene,select]);useEffect(()=>{if(!zoom)return;const distance=camera.position.length();camera.position.setLength(Math.min(13,Math.max(5,distance+zoom.delta)));camera.updateProjectionMatrix()},[zoom?.id,camera]);return null}
type Props={rotation:[number,number,number];resetKey:number;selection:Signal|null;zoom:ZoomSignal|null;explode?:number}
export function Scene({rotation,resetKey,selection,zoom,explode=1}:Props){return <Canvas className="ar-canvas" gl={{alpha:true,antialias:true}} onCreated={({gl})=>gl.setClearColor('#000000',0)} shadows frameloop="demand" performance={{min:.5}} camera={{position:[6.8,4.4,7.6],fov:34}} dpr={[1,1.5]}><ambientLight intensity={1.15}/><directionalLight castShadow position={[4,8,5]} intensity={3.2} color="#fff9e8"/><pointLight position={[-5,2,-3]} intensity={18} color="#ffffff"/><pointLight position={[4,1,4]} intensity={12} color="#ffffff"/><ModelError><Suspense fallback={<Loading/>}><Model rotation={rotation} explode={explode}/><Environment preset="city"/></Suspense></ModelError><OrbitControls key={resetKey} makeDefault enablePan={false} minDistance={5} maxDistance={13} minPolarAngle={.25} maxPolarAngle={Math.PI/1.9}/><GestureBridge selection={selection} zoom={zoom}/></Canvas>}
