import { Environment, Html, OrbitControls, useProgress } from '@react-three/drei'
import { Canvas, useThree } from '@react-three/fiber'
import { Component, Suspense, useEffect, type ReactNode } from 'react'
import { Raycaster, Vector2 } from 'three'
import { componentByModelName } from '../../data/components'
import { useLabStore } from '../../store/labStore'
import { Model } from './Model'
function Loading(){const{progress}=useProgress();return <Html center><div className="model-loading" role="status">Loading model - {Math.round(progress)}%</div></Html>}
class ModelError extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<Html center><div className="model-error" role="alert">The 3D model could not be loaded. Refresh to try again.</div></Html>:this.props.children}}
type Signal={id:number;x:number;y:number};type ZoomSignal={id:number;delta:number}
function GestureBridge({selection,zoom}:{selection:Signal|null;zoom:ZoomSignal|null}){const{camera,scene}=useThree();const select=useLabStore(s=>s.selectComponent);useEffect(()=>{if(!selection)return;scene.updateMatrixWorld(true);const raycaster=new Raycaster();raycaster.setFromCamera(new Vector2(selection.x*2-1,1-selection.y*2),camera);const hit=raycaster.intersectObjects(scene.children,true).find(item=>componentByModelName[item.object.name]);const id=hit?componentByModelName[hit.object.name]:undefined;if(id)select(id)},[selection?.id,camera,scene,select]);useEffect(()=>{if(!zoom)return;const distance=camera.position.length();camera.position.setLength(Math.min(13,Math.max(5,distance+zoom.delta)));camera.updateProjectionMatrix()},[zoom?.id,camera]);return null}
type Props={rotation:[number,number,number];resetKey:number;selection:Signal|null;zoom:ZoomSignal|null}
export function Scene({rotation,resetKey,selection,zoom}:Props){return <Canvas shadows frameloop="demand" performance={{min:.5}} camera={{position:[6.8,5.2,7.2],fov:35}} dpr={[1,1.5]}><color attach="background" args={['#0a1612']}/><fog attach="fog" args={['#0a1612',12,24]}/><ambientLight intensity={.65}/><directionalLight castShadow position={[4,8,5]} intensity={2.4} color="#fff4d0"/><pointLight position={[-5,2,-3]} intensity={12} color="#69e6b3"/><ModelError><Suspense fallback={<Loading/>}><Model rotation={rotation}/><Environment preset="city"/></Suspense></ModelError><gridHelper args={[18,18,'#214438','#132820']} position={[0,-.35,0]}/><OrbitControls key={resetKey} makeDefault enablePan={false} minDistance={5} maxDistance={13} minPolarAngle={.35} maxPolarAngle={Math.PI/2.1}/><GestureBridge selection={selection} zoom={zoom}/></Canvas>}
