import { Bot, Camera, Expand, Hand, Layers3, MousePointer2, RotateCcw, UserRound } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { ModelInfo } from '../components/3d/ModelInfo'
import { Scene } from '../components/3d/Scene'
import { CameraFeed } from '../components/camera/CameraFeed'
import { AccountPanel } from '../components/ui/AccountPanel'
import { TutorPanel } from '../components/ui/TutorPanel'
import { SystemStatus } from '../components/hud/SystemStatus'
import { InteractionReticle } from '../components/hud/InteractionReticle'
import { ComponentMetadata } from '../components/hud/ComponentMetadata'
import { EventStream } from '../components/hud/EventStream'
import { emitLabEvent } from '../events/labEvents'
import { components } from '../data/components'
import { InteractionController } from '../controllers/InteractionController'
import type { GestureResult } from '../gestures/GestureEngine'
import { useProgressSync } from '../hooks/useProgressSync'
import { useAuthStore } from '../store/authStore'
import { useLabStore } from '../store/labStore'

export function Lab(){
 const[tutorOpen,setTutorOpen]=useState(false);const[accountOpen,setAccountOpen]=useState(false);const[exploded,setExploded]=useState(false);const initializeAuth=useAuthStore(s=>s.initialize);const selected=useLabStore(s=>s.selectedComponent);const select=useLabStore(s=>s.selectComponent);useProgressSync()
 const[rotation,setRotation]=useState<[number,number,number]>([-.12,-.35,0]);const[resetKey,setResetKey]=useState(0);const[tracking,setTracking]=useState(false);const[gesture,setGesture]=useState<GestureResult|null>(null);const[grabbed,setGrabbed]=useState(false);const[selection,setSelection]=useState<{id:number;x:number;y:number}|null>(null);const[zoom,setZoom]=useState<{id:number;delta:number}|null>(null);const[nova,setNova]=useState<'idle'|'listening'|'speaking'>('idle');const[pulse,setPulse]=useState(0);const controller=useRef(new InteractionController());const signal=useRef(0)
 const turn=(x:number,y:number)=>setRotation(([rx,ry,rz])=>[Math.max(-1.15,Math.min(1.15,rx+x)),ry+y,rz]);const reset=()=>{setRotation([-.12,-.35,0]);setResetKey(k=>k+1)}
 const handleGesture=(result:GestureResult|null)=>{setGesture(result);if(result?.activated){setPulse(value=>value+1);emitLabEvent({type:'GESTURE',label:result.gesture})}if(!result){controller.current.reset();setGrabbed(false);return}const command=controller.current.update(result);setGrabbed(command.grabbed);if(command.rotationX||command.rotationY)turn(command.rotationX,command.rotationY);if(command.selectAt)setSelection({id:++signal.current,...command.selectAt});if(command.toggleExplode)setExploded(value=>!value);if(command.zoomDelta)setZoom({id:++signal.current,delta:command.zoomDelta})}
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='ArrowLeft')turn(0,-.15);if(event.key==='ArrowRight')turn(0,.15);if(event.key==='ArrowUp')turn(-.15,0);if(event.key==='ArrowDown')turn(.15,0);if(event.key==='Home')reset()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 useEffect(()=>{void initializeAuth()},[initializeAuth])
 useEffect(()=>{setExploded(false);setPulse(value=>value+1);emitLabEvent({type:'MODEL',label:'SELECTED',value:selected.toUpperCase()})},[selected])
 useEffect(()=>{setPulse(value=>value+1);emitLabEvent({type:'SPACE',label:exploded?'EXPLODED':'ASSEMBLED'})},[exploded])
 useEffect(()=>{setPulse(value=>value+1)},[nova])
 useEffect(()=>{const receive=(event:Event)=>setNova((event as CustomEvent<{state:'idle'|'listening'|'speaking'}>).detail.state);window.addEventListener('smaj:nova-state',receive);return()=>window.removeEventListener('smaj:nova-state',receive)},[])
 const gestureName=gesture?.gesture==='OPEN_PALM'?'Open palm':gesture?.gesture==='SWIPE_LEFT'?'Swipe left':gesture?.gesture==='SWIPE_RIGHT'?'Swipe right':gesture?.gesture==='POINT'?'Point':gesture?.gesture==='PINCH'?'Pinch':null
 const fullscreen=()=>document.documentElement.requestFullscreen?.()
 return <main className={`lab-shell ar-lab ${tracking?'camera-live':'camera-off'}`}><div className="ar-stage"><CameraFeed onTrackingChange={setTracking} onGesture={handleGesture}/><div className="ar-shade"/><Scene rotation={rotation} resetKey={resetKey} selection={selection} zoom={zoom} explode={exploded?1:0} tracking={tracking} hand={tracking&&gesture?gesture.screenPointer:null} selected={selected} pulse={pulse}/><header className="topbar ar-topbar"><div className="top-actions"><div className={`status ${tracking?'is-tracking':''}`}><span/>{grabbed?'Pinch control':gestureName??(tracking?'Hands online':'Camera ready')}</div><button onClick={()=>setTutorOpen(true)}><Bot size={15}/>Tutor</button><button onClick={()=>setAccountOpen(true)} aria-label="Learning account"><UserRound size={15}/></button></div></header><div className={`ar-lesson ${exploded?'is-open':'is-closed'}`}>{exploded?<ModelInfo/>:<aside className="inspect-panel" aria-label="Component inspection"><Layers3 size={16}/><div><strong>Component assembled</strong><span>Break it apart to reveal piece information.</span></div><button onClick={()=>setExploded(true)}>Inspect pieces</button></aside>}</div><nav className="ar-tools" aria-label="View tools"><button className="active" aria-label="Hand interaction"><Hand size={17}/></button><button onClick={reset} aria-label="Reset view"><RotateCcw size={17}/></button><button onClick={fullscreen} aria-label="Full screen"><Expand size={17}/></button><button className={exploded?'active':''} onClick={()=>setExploded(value=>!value)} aria-label="Break component into pieces"><Layers3 size={17}/></button></nav><div className="ar-title"><span>LAB 01 / COMPUTER SYSTEMS</span><strong>Spatial component viewer</strong></div>{tracking&&gesture?.gesture==='POINT'?<div className="gesture-cursor ar-hand-focus" style={{left:`${gesture.screenPointer.x*100}%`,top:`${gesture.screenPointer.y*100}%`}}><Hand size={36}/></div>:null}<nav className="model-dock" aria-label="Computer components">{components.map(item=><button key={item.id} className={selected===item.id?'active':''} onClick={()=>select(item.id)}><span>{item.shortName.slice(0,2).toUpperCase()}</span>{item.shortName}</button>)}</nav>{!tracking?<button className="camera-launch" onClick={()=>window.dispatchEvent(new Event('smaj:start-camera'))}><Camera size={16}/>Enable camera</button>:null}<div className="interaction-hint"><MousePointer2 size={14}/>{tracking?'Pinch: rotate | Move hand: zoom | Point: view | Open palm: break':'Enable camera for hand rotate, zoom, view and break'}</div></div><SystemStatus tracking={tracking} gesture={gesture} selected={selected} exploded={exploded} nova={nova}/><ComponentMetadata selected={selected} tracking={tracking} exploded={exploded}/><EventStream/><InteractionReticle/><TutorPanel open={tutorOpen} onClose={()=>setTutorOpen(false)} exploded={exploded} tracking={tracking} gesture={gestureName}/><AccountPanel open={accountOpen} onClose={()=>setAccountOpen(false)}/></main>
}
