import { FlaskConical, MousePointer2, RotateCcw } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { ModelInfo } from '../components/3d/ModelInfo'
import { Scene } from '../components/3d/Scene'
import { CameraFeed } from '../components/camera/CameraFeed'
import { InteractionController } from '../controllers/InteractionController'
import type { GestureResult } from '../gestures/GestureEngine'

export function Lab(){
 const[rotation,setRotation]=useState<[number,number,number]>([0,-.2,0]);const[resetKey,setResetKey]=useState(0);const[tracking,setTracking]=useState(false);const[gesture,setGesture]=useState<GestureResult|null>(null);const[grabbed,setGrabbed]=useState(false);const[selection,setSelection]=useState<{id:number;x:number;y:number}|null>(null);const[zoom,setZoom]=useState<{id:number;delta:number}|null>(null);const controller=useRef(new InteractionController());const signal=useRef(0)
 const turn=(x:number,y:number)=>setRotation(([rx,ry,rz])=>[Math.max(-1.15,Math.min(1.15,rx+x)),ry+y,rz]);const reset=()=>{setRotation([0,-.2,0]);setResetKey(k=>k+1)}
 const handleGesture=(result:GestureResult|null)=>{setGesture(result);if(!result){controller.current.reset();setGrabbed(false);return}const command=controller.current.update(result);setGrabbed(command.grabbed);if(command.rotationX||command.rotationY)turn(command.rotationX,command.rotationY);if(command.selectAt)setSelection({id:++signal.current,...command.selectAt});if(command.zoomDelta)setZoom({id:++signal.current,delta:command.zoomDelta})}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft')turn(0,-.15);if(e.key==='ArrowRight')turn(0,.15);if(e.key==='ArrowUp')turn(-.15,0);if(e.key==='ArrowDown')turn(.15,0);if(e.key==='Home')reset()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 const gestureName=gesture?.gesture==='OPEN_PALM'?'Open palm':gesture?.gesture==='SWIPE_LEFT'?'Swipe left':gesture?.gesture==='SWIPE_RIGHT'?'Swipe right':gesture?.gesture==='POINT'?'Point':gesture?.gesture==='PINCH'?'Pinch':null
 return <main className="lab-shell"><header className="topbar"><a className="brand" href={import.meta.env.BASE_URL} aria-label="SMAJ 3D Lab home"><span className="brand-mark"><FlaskConical size={19}/></span><span>SMAJ <strong>3D Lab</strong></span></a><div className="lab-title"><span>Lab 01</span><strong>Inside a computer</strong></div><div className={`status ${tracking?'is-tracking':''}`}><span/>{grabbed?'Pinch control active':gestureName??(tracking?'Hand tracking active':'Mouse mode')}</div></header><section className="workspace" aria-label="Interactive 3D computer lab"><div className="scene-wrap"><Scene rotation={rotation} resetKey={resetKey} selection={selection} zoom={zoom}/><div className="scene-label">Motherboard study model</div><div className="mode-chip"><MousePointer2 size={14}/>{tracking?'Point · Pinch · Swipe':'Select · Orbit · Zoom'}</div>{tracking&&gesture?.gesture==='POINT'?<div className="gesture-cursor" style={{left:`${gesture.screenPointer.x*100}%`,top:`${gesture.screenPointer.y*100}%`}}/>:null}<div className="model-controls" aria-label="Model rotation controls"><button onClick={()=>turn(0,-.15)} aria-label="Rotate model left">←</button><button onClick={()=>turn(-.15,0)} aria-label="Rotate model up">↑</button><button onClick={()=>turn(.15,0)} aria-label="Rotate model down">↓</button><button onClick={()=>turn(0,.15)} aria-label="Rotate model right">→</button><button onClick={reset} aria-label="Reset model view"><RotateCcw size={15}/></button></div></div><div className="side-rail"><ModelInfo/><CameraFeed onTrackingChange={setTracking} onGesture={handleGesture}/></div></section><footer className="lab-footer"><span>Learn. Explore. Interact.</span><span>{tracking?'Point to select · Pinch and move to rotate · Move closer to zoom':'Mouse, touch, and keyboard ready'}</span></footer></main>
}
