import { Camera, CameraOff, Hand, LoaderCircle, RefreshCw } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { GestureDiagnostics } from '../ui/GestureDiagnostics'
import { GestureEngine, type GestureResult } from '../../gestures/GestureEngine'
import { HandTracker, type SmoothedHand } from '../../vision/HandTracker'

type CameraState='idle'|'requesting'|'loading'|'tracking'|'no-hand'|'denied'|'unsupported'|'error'
type Props={onTrackingChange?:(active:boolean)=>void;onGesture?:(result:GestureResult|null)=>void}
const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]] as const
function drawHand(canvas:HTMLCanvasElement,hand:SmoothedHand|null){const context=canvas.getContext('2d');if(!context)return;context.clearRect(0,0,canvas.width,canvas.height);if(!hand)return;context.lineWidth=3;context.strokeStyle='rgba(117,225,168,.8)';context.beginPath();for(const[a,b]of connections){const from=hand.landmarks[a],to=hand.landmarks[b];context.moveTo(from.x*canvas.width,from.y*canvas.height);context.lineTo(to.x*canvas.width,to.y*canvas.height)}context.stroke();hand.landmarks.forEach((point,index)=>{context.beginPath();context.arc(point.x*canvas.width,point.y*canvas.height,index===0?6:4,0,Math.PI*2);context.fillStyle=index===4||index===8?'#f6c85f':'#75e1a8';context.fill()})}

export function CameraFeed({onTrackingChange,onGesture}:Props){
 const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),streamRef=useRef<MediaStream|null>(null),trackerRef=useRef<HandTracker|null>(null),engineRef=useRef(new GestureEngine()),frameRef=useRef(0),lastFrameRef=useRef(0)
 const[state,setState]=useState<CameraState>('idle');const[hand,setHand]=useState<SmoothedHand|null>(null);const[gesture,setGesture]=useState<GestureResult|null>(null)
 const stop=()=>{cancelAnimationFrame(frameRef.current);streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;trackerRef.current?.close();trackerRef.current=null;engineRef.current.reset();setHand(null);setGesture(null);onGesture?.(null);setState('idle');onTrackingChange?.(false)}
 useEffect(()=>stop,[])
 const start=async()=>{if(!navigator.mediaDevices?.getUserMedia){setState('unsupported');return}try{stop();setState('requesting');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});streamRef.current=stream;const video=videoRef.current;if(!video)return;video.srcObject=stream;await video.play();const canvas=canvasRef.current;if(canvas){canvas.width=video.videoWidth||640;canvas.height=video.videoHeight||480}setState('loading');const tracker=new HandTracker();trackerRef.current=tracker;await tracker.initialize();let missing=0;const detect=(time:number)=>{if(time-lastFrameRef.current>=33){lastFrameRef.current=time;const found=tracker.detect(video,time);setHand(found);if(found){missing=0;setState('tracking');const detected=engineRef.current.detect(found.landmarks,time);setGesture(detected);onGesture?.(detected);onTrackingChange?.(true)}else if(++missing>8){setState('no-hand');setGesture(null);onGesture?.(null);engineRef.current.reset();onTrackingChange?.(true)}if(canvasRef.current)drawHand(canvasRef.current,found)}frameRef.current=requestAnimationFrame(detect)};frameRef.current=requestAnimationFrame(detect)}catch(error){streamRef.current?.getTracks().forEach(track=>track.stop());const denied=error instanceof DOMException&&(error.name==='NotAllowedError'||error.name==='PermissionDeniedError');setState(denied?'denied':'error');onTrackingChange?.(false)}}
 useEffect(()=>{const request=()=>{void start()};window.addEventListener('smaj:start-camera',request);return()=>window.removeEventListener('smaj:start-camera',request)},[])
 const busy=state==='requesting'||state==='loading';const label=state==='tracking'?`${hand?.handedness??'Hand'} / ${Math.round((hand?.score??0)*100)}%`:state==='no-hand'?'Show one hand to the camera':state==='requesting'?'Waiting for camera permission...':state==='loading'?'Loading hand tracker...':state==='denied'?'Camera permission was denied':state==='unsupported'?'Camera access is not supported':state==='error'?'Camera or hand tracking could not start':'Camera stays off until you enable it.'
 return <section className={`camera-panel camera-${state}`} aria-label="Webcam hand tracking"><div className="camera-stage">{state==='idle'||state==='denied'||state==='unsupported'||state==='error'?<div className="camera-consent"><div className="camera-icon"><Camera size={22}/></div><strong>Enable hand tracking</strong><p>Your camera is processed live in this browser. SMAJ 3D Lab does not record or upload the video.</p><button onClick={start} disabled={state==='unsupported'}>{state==='denied'||state==='error'?<><RefreshCw size={15}/>Try again</>:<><Camera size={15}/>Enable camera</>}</button></div>:null}<video ref={videoRef} playsInline muted/><canvas ref={canvasRef}/>{busy?<div className="camera-busy"><LoaderCircle size={20}/><span>{label}</span></div>:null}</div>{state==='tracking'||state==='no-hand'?<GestureDiagnostics result={gesture}/>:null}<div className="camera-meta"><span className="camera-state"><span/>{label}</span>{state!=='idle'&&state!=='denied'&&state!=='unsupported'&&state!=='error'?<button onClick={stop} aria-label="Turn off camera"><CameraOff size={15}/>Off</button>:<Hand size={17}/>}</div></section>
}
