import { Mic, MicOff, Volume2, VolumeX, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { componentById } from '../../data/components'
import { askTutor, NovaError, type NovaContext, type TutorMessage } from '../../services/tutor'
import { useLabStore } from '../../store/labStore'

type RecognitionResultEvent={results:ArrayLike<{0:{transcript:string};isFinal?:boolean}>}
type RecognitionErrorEvent={error?:string;message?:string}
type Recognition={continuous:boolean;interimResults:boolean;lang:string;onresult:((event:RecognitionResultEvent)=>void)|null;onend:(()=>void)|null;onerror:((event:RecognitionErrorEvent)=>void)|null;start:()=>void;stop:()=>void}
type Position={x:number;y:number}
type Props={open:boolean;onClose:()=>void;exploded:boolean;tracking:boolean;gesture:string|null}

export function TutorPanel({open,onClose,exploded,tracking,gesture}:Props){
 const selected=useLabStore(s=>s.selectedComponent),visited=useLabStore(s=>s.visited),quizResults=useLabStore(s=>s.quizResults),component=componentById[selected]
 const intro=()=>({role:'tutor' as const,text:`You are exploring the ${component.name}. Speak to ask me anything.`})
 const[messages,setMessages]=useState<TutorMessage[]>([intro()]),[busy,setBusy]=useState(false),[voiceEnabled,setVoiceEnabled]=useState(true),[speaking,setSpeaking]=useState(false),[listenEnabled,setListenEnabled]=useState(false),[recognizing,setRecognizing]=useState(false),[position,setPosition]=useState<Position>({x:24,y:150})
 const recognition=useRef<Recognition|null>(null),listenWanted=useRef(false),face=useRef<HTMLDivElement>(null),drag=useRef<{dx:number;dy:number}|null>(null),lastSpoken=useRef(''),request=useRef<AbortController|null>(null)
 const latest=messages[messages.length-1]??intro()
 const context=useMemo<NovaContext>(()=>({componentId:selected,lesson:component.lesson,interactionState:exploded?'exploded':'assembled',handTracking:tracking,gesture,visited,passed:Object.entries(quizResults).filter(([,passed])=>passed).map(([id])=>id as typeof selected),availableActions:['rotate model','zoom model','select a component','switch assembled or exploded view','inspect component details','take the component quiz']}),[selected,component.lesson,exploded,tracking,gesture,visited,quizResults])
 useEffect(()=>{setMessages(current=>current.some(message=>message.role==='student')?current:[intro()]);lastSpoken.current=''},[selected])
 useEffect(()=>{if(open)setPosition(value=>value.x===24&&value.y===150?{x:Math.max(12,window.innerWidth-150),y:150}:value)},[open])
 const getRecognition=useCallback(()=>{const speechWindow=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const RecognitionClass=speechWindow.SpeechRecognition??speechWindow.webkitSpeechRecognition;return RecognitionClass?new RecognitionClass():null},[])
 const interrupt=useCallback(()=>{request.current?.abort();request.current=null;window.speechSynthesis?.cancel();setSpeaking(false);setBusy(false)},[])
 const send=useCallback(async(text:string)=>{const question=text.trim();if(!question||busy)return;interrupt();const history=messages.slice(-12);const controller=new AbortController();request.current=controller;setMessages(current=>[...current,{role:'student',text:question},{role:'tutor',text:''}]);setBusy(true);try{const result=await askTutor({message:question,history,context,signal:controller.signal,onDelta:(_delta,fullText)=>setMessages(current=>current.map((item,index)=>index===current.length-1?{role:'tutor',text:fullText}:item))});setMessages(current=>current.map((item,index)=>index===current.length-1?{role:'tutor',text:result.answer}:item))}catch(error){if(controller.signal.aborted){setMessages(current=>current.at(-1)?.text?current:current.slice(0,-1));return}const message=error instanceof NovaError?error.message:error instanceof Error?error.message:'NOVA could not complete the request.';setMessages(current=>current.map((item,index)=>index===current.length-1?{role:'tutor',text:`NOVA error: ${message}`,error:true}:item))}finally{if(request.current===controller)request.current=null;setBusy(false)}},[busy,context,interrupt,messages])
 const beginListening=useCallback(()=>{if(!listenWanted.current||recognition.current||speaking)return;const instance=getRecognition();if(!instance){listenWanted.current=false;setListenEnabled(false);setMessages(current=>[...current,{role:'tutor',text:'Voice input is unavailable because this browser does not support speech recognition.',error:true}]);return}recognition.current=instance;instance.continuous=true;instance.interimResults=false;instance.lang=navigator.language||'en-US';instance.onresult=event=>{const result=event.results[event.results.length-1];const text=result?.[0]?.transcript?.trim();if(text){instance.stop();void send(text)}};instance.onerror=event=>{setRecognizing(false);if(event.error&&event.error!=='aborted'&&event.error!=='no-speech')setMessages(current=>[...current,{role:'tutor',text:`Microphone error: ${event.message||event.error}`,error:true}])};instance.onend=()=>{recognition.current=null;setRecognizing(false);if(listenWanted.current&&!speaking)window.setTimeout(beginListening,250)};try{instance.start();setRecognizing(true)}catch(error){recognition.current=null;setRecognizing(false);setMessages(current=>[...current,{role:'tutor',text:`Microphone error: ${error instanceof Error?error.message:'could not start listening'}`,error:true}])}},[getRecognition,send,speaking])
 useEffect(()=>{window.dispatchEvent(new CustomEvent('smaj:nova-state',{detail:{state:speaking?'speaking':recognizing?'listening':'idle'}}))},[speaking,recognizing])
 useEffect(()=>{listenWanted.current=listenEnabled;if(listenEnabled)beginListening();else{recognition.current?.stop();recognition.current=null;setRecognizing(false)}},[listenEnabled,beginListening])
 useEffect(()=>{if(!open){listenWanted.current=false;recognition.current?.stop();recognition.current=null;interrupt();setRecognizing(false);return}if(busy||latest.error||!voiceEnabled||latest.role!=='tutor'||!latest.text||latest.text===lastSpoken.current||!('speechSynthesis'in window))return;recognition.current?.stop();recognition.current=null;const speech=new SpeechSynthesisUtterance(latest.text);speech.rate=.96;speech.pitch=1.04;speech.onstart=()=>setSpeaking(true);speech.onend=()=>{setSpeaking(false);if(listenWanted.current)window.setTimeout(beginListening,180)};speech.onerror=()=>setSpeaking(false);lastSpoken.current=latest.text;window.speechSynthesis.cancel();window.speechSynthesis.speak(speech)},[latest,busy,open,voiceEnabled,beginListening,interrupt])
 useEffect(()=>{const follow=(event:PointerEvent)=>{const node=face.current;if(!node)return;const box=node.getBoundingClientRect(),dx=Math.max(-3,Math.min(3,(event.clientX-(box.left+box.width/2))/22)),dy=Math.max(-2,Math.min(2,(event.clientY-(box.top+box.height/2))/22));node.style.setProperty('--look-x',`${dx*1.6}deg`);node.style.setProperty('--look-y',`${-dy*1.6}deg`)};window.addEventListener('pointermove',follow);return()=>window.removeEventListener('pointermove',follow)},[])
 useEffect(()=>()=>{listenWanted.current=false;recognition.current?.stop();request.current?.abort();window.speechSynthesis?.cancel()},[])
 const toggleListen=()=>{if(speaking||busy){interrupt();listenWanted.current=true;setListenEnabled(true);window.setTimeout(beginListening,0);return}listenWanted.current=!listenEnabled;setListenEnabled(value=>!value)}
 const toggleVoice=()=>{if(voiceEnabled)interrupt();else lastSpoken.current='';setVoiceEnabled(value=>!value)}
 const startDrag=(event:ReactPointerEvent<HTMLElement>)=>{if((event.target as HTMLElement).closest('button'))return;drag.current={dx:event.clientX-position.x,dy:event.clientY-position.y};event.currentTarget.setPointerCapture(event.pointerId)}
 const moveDrag=(event:ReactPointerEvent<HTMLElement>)=>{if(!drag.current)return;setPosition({x:Math.max(8,Math.min(window.innerWidth-126,event.clientX-drag.current.dx)),y:Math.max(58,Math.min(window.innerHeight-166,event.clientY-drag.current.dy))})}
 const endDrag=()=>{drag.current=null}
 if(!open)return null
 return <aside className="ai-orb" aria-label="AI learning tutor" style={{left:position.x,top:position.y}} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><div className={`ai-face ${speaking?'speaking':''} ${recognizing?'listening':''}`} role="img" aria-label="SMAJ AI face" ref={face}><img className="face-frame base" src={`${import.meta.env.BASE_URL}assets/smaj-ai-face.png`} alt="" draggable={false}/><img className="face-frame talk" src={`${import.meta.env.BASE_URL}assets/smaj-ai-face-talk.png`} alt="" draggable={false}/><img className="face-frame blink" src={`${import.meta.env.BASE_URL}assets/smaj-ai-face-blink.png`} alt="" draggable={false}/></div><div className="ai-orb-actions"><button onClick={toggleListen} className={recognizing?'active':''} aria-label={listenEnabled?'Stop listening':'Start voice conversation'}>{listenEnabled?<MicOff size={15}/>:<Mic size={15}/>}</button><button onClick={toggleVoice} aria-label={voiceEnabled?'Mute AI voice':'Enable AI voice'}>{voiceEnabled?<Volume2 size={15}/>:<VolumeX size={15}/>}</button><button onClick={onClose} aria-label="Close tutor"><X size={15}/></button></div><div className={`ai-speech ${latest.role} ${busy?'thinking':''} ${latest.error?'error':''}`} aria-live="polite">{latest.text||(busy?'NOVA is streaming...':'')}</div><small>{recognizing?'LISTENING — SPEAK NOW':speaking?'SPEAKING — TAP MIC TO INTERRUPT':busy?'OPENAI STREAMING':listenEnabled?'MIC READY':'CLICK MIC TO TALK'}</small></aside>
}
