import { Mic, MicOff, Volume2, VolumeX, X } from 'lucide-react'
import { useCallback, useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react'
import { componentById } from '../../data/components'
import { askTutor, type TutorMessage } from '../../services/tutor'
import { useLabStore } from '../../store/labStore'

type RecognitionResultEvent={results:ArrayLike<{0:{transcript:string};isFinal?:boolean}>}
type Recognition={continuous:boolean;interimResults:boolean;lang:string;onresult:((event:RecognitionResultEvent)=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null;start:()=>void;stop:()=>void}
type Position={x:number;y:number}

export function TutorPanel({open,onClose}:{open:boolean;onClose:()=>void}){
 const selected=useLabStore(s=>s.selectedComponent),component=componentById[selected]
 const[latest,setLatest]=useState<TutorMessage>({role:'tutor',text:`You are exploring the ${component.name}. Speak to ask me anything.`}),[busy,setBusy]=useState(false),[voiceEnabled,setVoiceEnabled]=useState(true),[speaking,setSpeaking]=useState(false),[listenEnabled,setListenEnabled]=useState(false),[recognizing,setRecognizing]=useState(false),[position,setPosition]=useState<Position>({x:24,y:150})
 const recognition=useRef<Recognition|null>(null),listenWanted=useRef(false),face=useRef<HTMLDivElement>(null),drag=useRef<{dx:number;dy:number}|null>(null),lastSpoken=useRef('')
 useEffect(()=>{setLatest({role:'tutor',text:`You are exploring the ${component.name}. Speak to ask me anything.`});lastSpoken.current=''},[selected])
 useEffect(()=>{if(open)setPosition(value=>value.x===24&&value.y===150?{x:Math.max(12,window.innerWidth-122),y:150}:value)},[open])
 const getRecognition=useCallback(()=>{const speechWindow=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const RecognitionClass=speechWindow.SpeechRecognition??speechWindow.webkitSpeechRecognition;return RecognitionClass?new RecognitionClass():null},[])
 const send=useCallback(async(text:string)=>{const question=text.trim();if(!question||busy)return;setLatest({role:'student',text:question});setBusy(true);try{const result=await askTutor(selected,'question',question);setLatest({role:'tutor',text:result.answer})}catch{setLatest({role:'tutor',text:'I could not reach the online intelligence. I can still explain this component with local lesson knowledge.'})}finally{setBusy(false)}},[busy,selected])
 const beginListening=useCallback(()=>{if(!listenWanted.current||recognition.current||speaking)return;const instance=getRecognition();if(!instance){listenWanted.current=false;setListenEnabled(false);setLatest({role:'tutor',text:'This browser does not support speech recognition. Try Microsoft Edge or Google Chrome.'});return}recognition.current=instance;instance.continuous=true;instance.interimResults=false;instance.lang=navigator.language||'en-US';instance.onresult=event=>{const result=event.results[event.results.length-1];const text=result?.[0]?.transcript?.trim();if(text){instance.stop();void send(text)}};instance.onerror=()=>{setRecognizing(false)};instance.onend=()=>{recognition.current=null;setRecognizing(false);if(listenWanted.current&&!speaking)window.setTimeout(beginListening,250)};try{instance.start();setRecognizing(true)}catch{recognition.current=null;setRecognizing(false)}},[getRecognition,send,speaking])
 useEffect(()=>{listenWanted.current=listenEnabled;if(listenEnabled)beginListening();else{recognition.current?.stop();recognition.current=null;setRecognizing(false)}},[listenEnabled,beginListening])
 useEffect(()=>{if(!open){listenWanted.current=false;recognition.current?.stop();recognition.current=null;window.speechSynthesis?.cancel();setSpeaking(false);setRecognizing(false);return}if(!voiceEnabled||latest.role!=='tutor'||latest.text===lastSpoken.current||!('speechSynthesis'in window))return;recognition.current?.stop();recognition.current=null;const speech=new SpeechSynthesisUtterance(latest.text);speech.rate=.96;speech.pitch=1.04;speech.onstart=()=>setSpeaking(true);speech.onend=()=>{setSpeaking(false);if(listenWanted.current)window.setTimeout(beginListening,180)};speech.onerror=()=>setSpeaking(false);lastSpoken.current=latest.text;window.speechSynthesis.cancel();window.speechSynthesis.speak(speech)},[latest,open,voiceEnabled,beginListening])
 useEffect(()=>{const follow=(event:PointerEvent)=>{const node=face.current;if(!node)return;const box=node.getBoundingClientRect(),dx=Math.max(-3,Math.min(3,(event.clientX-(box.left+box.width/2))/22)),dy=Math.max(-2,Math.min(2,(event.clientY-(box.top+box.height/2))/22));node.style.setProperty('--eye-x',`${dx}px`);node.style.setProperty('--eye-y',`${dy}px`)};window.addEventListener('pointermove',follow);return()=>window.removeEventListener('pointermove',follow)},[])
 useEffect(()=>()=>{listenWanted.current=false;recognition.current?.stop();window.speechSynthesis?.cancel()},[])
 const toggleListen=()=>{listenWanted.current=!listenEnabled;setListenEnabled(value=>!value)}
 const toggleVoice=()=>{if(voiceEnabled){window.speechSynthesis?.cancel();setSpeaking(false)}else lastSpoken.current='';setVoiceEnabled(value=>!value)}
 const startDrag=(event:ReactPointerEvent<HTMLElement>)=>{if((event.target as HTMLElement).closest('button'))return;drag.current={dx:event.clientX-position.x,dy:event.clientY-position.y};event.currentTarget.setPointerCapture(event.pointerId)}
 const moveDrag=(event:ReactPointerEvent<HTMLElement>)=>{if(!drag.current)return;setPosition({x:Math.max(8,Math.min(window.innerWidth-104,event.clientX-drag.current.dx)),y:Math.max(58,Math.min(window.innerHeight-126,event.clientY-drag.current.dy))})}
 const endDrag=()=>{drag.current=null}
 if(!open)return null
 return <aside className="ai-orb" aria-label="AI learning tutor" style={{left:position.x,top:position.y}} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><div className={`ai-face ${speaking?'speaking':''} ${recognizing?'listening':''}`} role="img" aria-label="SMAJ AI face" ref={face}><i/><i/><b/></div><div className="ai-orb-actions"><button onClick={toggleListen} className={recognizing?'active':''} aria-label={listenEnabled?'Stop listening':'Start voice conversation'}>{listenEnabled?<MicOff size={15}/>:<Mic size={15}/>}</button><button onClick={toggleVoice} aria-label={voiceEnabled?'Mute AI voice':'Enable AI voice'}>{voiceEnabled?<Volume2 size={15}/>:<VolumeX size={15}/>}</button><button onClick={onClose} aria-label="Close tutor"><X size={15}/></button></div><div className={`ai-speech ${latest.role} ${busy?'thinking':''}`} aria-live="polite">{busy?'Thinking...':latest.text}</div><small>{recognizing?'LISTENING — SPEAK NOW':speaking?'SPEAKING':listenEnabled?'MIC READY':'CLICK MIC TO TALK'}</small></aside>
}